version: '3.9'

networks:
  default:
    driver: bridge

services:
  postgres:
    image: postgres:15.8
    restart: unless-stopped
    container_name: postgres
    ports:
      - "${DB_POSTGRES_PORT}:5432"
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    networks:
      - default
    env_file:
      - ./.env
    environment:
      TZ: "America/Sao_Paulo"
      PGTZ: "America/Sao_Paulo"
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ${DB_POSTGRES_DB}
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}